# Generated by Django 3.1.3 on 2021-09-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pk', models.CharField(max_length=300, unique=True)),
                ('number_1', models.IntegerField()),
                ('number_2', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
